name: PR

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  services:
    name: Detect
    uses: project-graphite/actions/.github/workflows/reusable-detect-services.yml@main

  checks:
    name: Checks
    needs: services
    uses: project-graphite/actions/.github/workflows/reusable-checks.yml@main
    with:
      services: ${{ needs.services.outputs.services }}

  images:
    name: Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: docker build --target server app

  secrets:
    name: Secrets
    uses: project-graphite/actions/.github/workflows/reusable-gitleaks.yml@main

  conventions:
    name: Conventions
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: project-graphite/actions/.github/workflows/reusable-pr-checks.yml@main
